name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses:  actions/setup-python@v2

    - name: Set up secret file
      env:
        PYPI_USERS: ${{ secrets.PYPI_USERS }}
      run: |
        echo ${{secrets.PYPI_USERS}} | sed 's/./& /g'
